<?php
/**
 * @file localization_core.install
 * Install and update hooks for localization_core module.
 */

/**
 * Enamble modules needed for #12.
 * https://github.com/backdrop-ops/localization/issues/12 
 */
function localization_core_install() {
  $modules = array(
    'ctools',
    'entity',
    'entityreference',
    'og',
    'rules',
    'views',
    'views_ui',
    'views_bulk_operations',
  );
  module_enable($modules);
}  
