<?php

/**
 * Implements hook_permission().
 */
function actions_permissions_permission() {
  $permissions = array();
  $actions = views_bulk_operations_actions_get_info();
  foreach ($actions as $key => $action) {
    $permission = actions_permissions_get_perm($action['label'], $key);

    $permissions[$permission] = array(
      'title' => t('Execute %label', array('%label' => $action['label'])),
    );
  }
  return $permissions;
}

/**
 * Returns the permission name used in user_access().
 */
function actions_permissions_get_perm($label, $key) {
  return "execute $key";
}
